from PyQt5 import QtCore, QtGui, QtWidgets, QtQuickWidgets
import dock, menuStatusBar


class firstConfiguration:
    def contain(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 431)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.first_label = QtWidgets.QLabel(self.central_widget)
        self.first_label.setGeometry(QtCore.QRect(20, 0, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.first_label.setFont(font)
        self.first_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.first_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_label.setObjectName("first_label")
        self.label_language = QtWidgets.QLabel(self.central_widget)
        self.label_language.setGeometry(QtCore.QRect(40, 60, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_language.setFont(font)
        self.label_language.setObjectName("label_language")
        self.combo_box_language = QtWidgets.QComboBox(self.central_widget)
        self.combo_box_language.setGeometry(QtCore.QRect(130, 60, 141, 22))
        self.combo_box_language.setObjectName("combo_box_language")
        self.combo_box_language.addItem("")
        self.combo_box_language.addItem("")
        self.line_3 = QtWidgets.QFrame(self.central_widget)
        self.line_3.setGeometry(QtCore.QRect(20, 370, 531, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.button_start = QtWidgets.QPushButton(self.central_widget)
        self.button_start.setGeometry(QtCore.QRect(460, 390, 75, 23))
        self.button_start.setObjectName("button_start")

        self.label_mode = QtWidgets.QLabel(self.central_widget)
        self.label_mode.setGeometry(QtCore.QRect(40, 140, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.line_1 = QtWidgets.QFrame(self.central_widget)
        self.line_1.setGeometry(QtCore.QRect(20, 40, 531, 16))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.label_language_2 = QtWidgets.QLabel(self.central_widget)
        self.label_language_2.setGeometry(QtCore.QRect(40, 90, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_language_2.setFont(font)
        self.label_language_2.setObjectName("label_language_2")
        self.line_5 = QtWidgets.QFrame(self.central_widget)
        self.line_5.setGeometry(QtCore.QRect(20, 120, 531, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.fontComboBox = QtWidgets.QFontComboBox(self.central_widget)
        self.fontComboBox.setGeometry(QtCore.QRect(130, 90, 141, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.stackedWidget = QtWidgets.QStackedWidget(self.central_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(290, 140, 231, 221))
        self.stackedWidget.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.comboBox = QtWidgets.QComboBox(self.central_widget)
        self.comboBox.setGeometry(QtCore.QRect(130, 140, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.central_widget)
        self.line.setGeometry(QtCore.QRect(280, 47, 3, 80))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_language_3 = QtWidgets.QLabel(self.central_widget)
        self.label_language_3.setGeometry(QtCore.QRect(300, 60, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_language_3.setFont(font)
        self.label_language_3.setObjectName("label_language_3")
        self.combo_box_language_2 = QtWidgets.QComboBox(self.central_widget)
        self.combo_box_language_2.setGeometry(QtCore.QRect(380, 60, 141, 22))
        self.combo_box_language_2.setObjectName("combo_box_language_2")
        self.combo_box_language_2.addItem("")
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "First Time Configuration"))
        self.first_label.setText(_translate("MainWindow", "GemChart configuration:"))
        self.label_language.setText(_translate("MainWindow", "Language:"))
        self.combo_box_language.setItemText(0, _translate("MainWindow", "English"))
        self.combo_box_language.setItemText(1, _translate("MainWindow", "Polish"))
        self.button_start.setText(_translate("MainWindow", "START"))
        self.label_mode.setText(_translate("MainWindow", "Theme"))
        self.label_language_2.setText(_translate("MainWindow", "Font:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Eclippy"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Ubuntu"))
        self.label_language_3.setText(_translate("MainWindow", "Resolution:"))
        self.combo_box_language_2.setItemText(0, _translate("MainWindow", "800 x 600"))


class main:
    def contain(self, main_window):
            main_window.resize(800, 600)
            main_window.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
            main_window.setTabShape(QtWidgets.QTabWidget.Triangular)
            main_window.setWindowIcon(QtGui.QIcon("Image/Icons/blank-logo.ico"))
            main_window.setWindowTitle("GenChart")

            self.centralwidget = QtWidgets.QWidget(main_window)
            self.centralwidget.setObjectName("centralwidget")
            main_window.setCentralWidget(self.centralwidget)

            self.central_layout = QtWidgets.QVBoxLayout(self.centralwidget)

            showDock = dock.Dock(main_window, self.central_layout)
            showDock.right_up()
            showDock.right_down()
            showDock.left_chart()

            menu_bar = menuStatusBar.MenuBar(main_window, showDock)
            status_bar = menuStatusBar.StatusBar(main_window)

            QtCore.QMetaObject.connectSlotsByName(main_window)

            """
                style_css = "Theme/darkorange.css"
                style = open(style_css, "r")
                app.setStyleSheet(style.read())
            """